/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package depresion;

//import com.mysql.jdbc.Connection;
import java.io.*;
import java.util.*;
import weka.core.*;
import weka.classifiers.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.ObjectInputStream;
import java.io.PrintWriter;
import weka.classifiers.Classifier;
import weka.core.Instances;
import java.io.IOException;
import java.io.*;
import weka.attributeSelection.*;
import weka.core.Instances;
import weka.core.*;
import weka.classifiers.*;
import weka.classifiers.Classifier;
import weka.classifiers.functions.SMO;
import weka.core.Instance;
import weka.core.converters.ConverterUtils;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import weka.classifiers.Classifier;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.lang.*;
import java.io.*;
import weka.classifiers.*;
import weka.core.Instances;
//import java.sql.PreparedStatement;
//import javax.swing.JOptionPane;
/**
 *
 * @author liz
 */
public class Prediccion1 extends javax.swing.JFrame {
        /*Conexion con = new Conexion();
        PreparedStatement pst;
        Connection conn = (Connection) con.getConexion();*/

    /**
     * Creates new form 
     */
    public Prediccion1() {
        initComponents();
        setTitle("Encuesta de Depresion paa Predecir");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        buttonGroup21 = new javax.swing.ButtonGroup();
        buttonGroup22 = new javax.swing.ButtonGroup();
        buttonGroup23 = new javax.swing.ButtonGroup();
        buttonGroup24 = new javax.swing.ButtonGroup();
        buttonGroup25 = new javax.swing.ButtonGroup();
        buttonGroup26 = new javax.swing.ButtonGroup();
        buttonGroup27 = new javax.swing.ButtonGroup();
        buttonGroup28 = new javax.swing.ButtonGroup();
        buttonGroup29 = new javax.swing.ButtonGroup();
        buttonGroup30 = new javax.swing.ButtonGroup();
        buttonGroup31 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        p1a = new javax.swing.JRadioButton();
        p1b = new javax.swing.JRadioButton();
        p1c = new javax.swing.JRadioButton();
        label2 = new java.awt.Label();
        p2a = new javax.swing.JRadioButton();
        p2b = new javax.swing.JRadioButton();
        p2c = new javax.swing.JRadioButton();
        label3 = new java.awt.Label();
        p3a = new javax.swing.JRadioButton();
        p3b = new javax.swing.JRadioButton();
        p3c = new javax.swing.JRadioButton();
        label4 = new java.awt.Label();
        p4a = new javax.swing.JRadioButton();
        p4b = new javax.swing.JRadioButton();
        p4c = new javax.swing.JRadioButton();
        label5 = new java.awt.Label();
        p5a = new javax.swing.JRadioButton();
        p5b = new javax.swing.JRadioButton();
        p5c = new javax.swing.JRadioButton();
        label6 = new java.awt.Label();
        p6a = new javax.swing.JRadioButton();
        p6b = new javax.swing.JRadioButton();
        p6c = new javax.swing.JRadioButton();
        label7 = new java.awt.Label();
        p7a = new javax.swing.JRadioButton();
        p7b = new javax.swing.JRadioButton();
        p7c = new javax.swing.JRadioButton();
        label8 = new java.awt.Label();
        p8a = new javax.swing.JRadioButton();
        p8b = new javax.swing.JRadioButton();
        p8c = new javax.swing.JRadioButton();
        label9 = new java.awt.Label();
        p9a = new javax.swing.JRadioButton();
        p9b = new javax.swing.JRadioButton();
        p9c = new javax.swing.JRadioButton();
        label10 = new java.awt.Label();
        p10a = new javax.swing.JRadioButton();
        p10b = new javax.swing.JRadioButton();
        p10c = new javax.swing.JRadioButton();
        label11 = new java.awt.Label();
        p11a = new javax.swing.JRadioButton();
        p11b = new javax.swing.JRadioButton();
        p11c = new javax.swing.JRadioButton();
        label12 = new java.awt.Label();
        p12a = new javax.swing.JRadioButton();
        p12b = new javax.swing.JRadioButton();
        p12c = new javax.swing.JRadioButton();
        label13 = new java.awt.Label();
        p13a = new javax.swing.JRadioButton();
        p13b = new javax.swing.JRadioButton();
        p13c = new javax.swing.JRadioButton();
        label14 = new java.awt.Label();
        p14a = new javax.swing.JRadioButton();
        p14b = new javax.swing.JRadioButton();
        p14c = new javax.swing.JRadioButton();
        label15 = new java.awt.Label();
        p15a = new javax.swing.JRadioButton();
        p15b = new javax.swing.JRadioButton();
        p15c = new javax.swing.JRadioButton();
        label16 = new java.awt.Label();
        p16a = new javax.swing.JRadioButton();
        p16b = new javax.swing.JRadioButton();
        p16c = new javax.swing.JRadioButton();
        label17 = new java.awt.Label();
        p17a = new javax.swing.JRadioButton();
        p17b = new javax.swing.JRadioButton();
        p17c = new javax.swing.JRadioButton();
        label18 = new java.awt.Label();
        p18a = new javax.swing.JRadioButton();
        p18b = new javax.swing.JRadioButton();
        p18c = new javax.swing.JRadioButton();
        label19 = new java.awt.Label();
        p19a = new javax.swing.JRadioButton();
        p19b = new javax.swing.JRadioButton();
        p19c = new javax.swing.JRadioButton();
        label20 = new java.awt.Label();
        p20a = new javax.swing.JRadioButton();
        p20b = new javax.swing.JRadioButton();
        p20c = new javax.swing.JRadioButton();
        label21 = new java.awt.Label();
        p21a = new javax.swing.JRadioButton();
        p21b = new javax.swing.JRadioButton();
        p21c = new javax.swing.JRadioButton();
        label22 = new java.awt.Label();
        p22a = new javax.swing.JRadioButton();
        p22b = new javax.swing.JRadioButton();
        p22c = new javax.swing.JRadioButton();
        label23 = new java.awt.Label();
        p23a = new javax.swing.JRadioButton();
        p23b = new javax.swing.JRadioButton();
        p23c = new javax.swing.JRadioButton();
        label24 = new java.awt.Label();
        p24a = new javax.swing.JRadioButton();
        p24b = new javax.swing.JRadioButton();
        p24c = new javax.swing.JRadioButton();
        label25 = new java.awt.Label();
        p25a = new javax.swing.JRadioButton();
        p25b = new javax.swing.JRadioButton();
        p25c = new javax.swing.JRadioButton();
        label26 = new java.awt.Label();
        p26a = new javax.swing.JRadioButton();
        p26b = new javax.swing.JRadioButton();
        p26c = new javax.swing.JRadioButton();
        label27 = new java.awt.Label();
        p29a = new javax.swing.JRadioButton();
        p27b = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        p27c = new javax.swing.JRadioButton();
        label28 = new java.awt.Label();
        p27a = new javax.swing.JRadioButton();
        p28b = new javax.swing.JRadioButton();
        p28c = new javax.swing.JRadioButton();
        label29 = new java.awt.Label();
        p28a = new javax.swing.JRadioButton();
        p29b = new javax.swing.JRadioButton();
        p29c = new javax.swing.JRadioButton();
        label30 = new java.awt.Label();
        p31a = new javax.swing.JRadioButton();
        p31b = new javax.swing.JRadioButton();
        label31 = new java.awt.Label();
        p30a = new javax.swing.JRadioButton();
        p30b = new javax.swing.JRadioButton();
        p30c = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label1.setText("1.-¿A que nivel socio-econimico perteneces?");

        buttonGroup1.add(p1a);
        p1a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p1a.setText("a) Alto    ");
        p1a.setName("1"); // NOI18N
        p1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1aActionPerformed(evt);
            }
        });

        buttonGroup1.add(p1b);
        p1b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p1b.setText("b) Medio");
        p1b.setName("2"); // NOI18N
        p1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1bActionPerformed(evt);
            }
        });

        buttonGroup1.add(p1c);
        p1c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p1c.setText("c) Bajo");
        p1c.setName("3"); // NOI18N
        p1c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1cActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label2.setText("2-¿Cuál fue tu ultimo logro académico?");

        buttonGroup2.add(p2a);
        p2a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p2a.setText("a) Prepa    ");
        p2a.setName("1"); // NOI18N
        p2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2aActionPerformed(evt);
            }
        });

        buttonGroup2.add(p2b);
        p2b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p2b.setText("b) Secundaria     ");
        p2b.setName("2"); // NOI18N
        p2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2bActionPerformed(evt);
            }
        });

        buttonGroup2.add(p2c);
        p2c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p2c.setText("c) Primaria");
        p2c.setName("3"); // NOI18N
        p2c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2cActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label3.setText("3.-¿Generalmente cuál es tu promedio?");

        buttonGroup3.add(p3a);
        p3a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p3a.setText("a)  9-10    ");
        p3a.setName("1"); // NOI18N

        buttonGroup3.add(p3b);
        p3b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p3b.setText("b) 7-8    ");
        p3b.setName("2"); // NOI18N
        p3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3bActionPerformed(evt);
            }
        });

        buttonGroup3.add(p3c);
        p3c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p3c.setText("c) Menor a 6");
        p3c.setName("3"); // NOI18N
        p3c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3cActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label4.setText("4.-¿Cuántas materias sueles dejar por ciclo (bimestre, trimestre, cuatrimestre, etc)?");

        buttonGroup4.add(p4a);
        p4a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p4a.setText("a) 1 a 2    ");
        p4a.setName("1"); // NOI18N

        buttonGroup4.add(p4b);
        p4b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p4b.setText("b)3 en adelante     ");
        p4b.setName("2"); // NOI18N

        buttonGroup4.add(p4c);
        p4c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p4c.setText("c) Nunca dejo");
        p4c.setName("3"); // NOI18N

        label5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label5.setText("5.-¿Cómo consideras el ambiente en tu salón de clases?");

        buttonGroup5.add(p5a);
        p5a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p5a.setText("a) Muy bueno    ");
        p5a.setName("1"); // NOI18N

        buttonGroup5.add(p5b);
        p5b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p5b.setText("b) Bueno     ");
        p5b.setName("2"); // NOI18N

        buttonGroup5.add(p5c);
        p5c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p5c.setText("c) Pésimo ");
        p5c.setName("3"); // NOI18N
        p5c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5cActionPerformed(evt);
            }
        });

        label6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label6.setText("6.-¿Qué tan bueno consideras que eres en lo que estudias?");

        buttonGroup6.add(p6a);
        p6a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p6a.setText("a) Muy bueno    ");
        p6a.setName("1"); // NOI18N

        buttonGroup6.add(p6b);
        p6b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p6b.setText("b) Bueno     ");
        p6b.setName("2"); // NOI18N

        buttonGroup6.add(p6c);
        p6c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p6c.setText("c) Pésimo ");
        p6c.setName("3"); // NOI18N
        p6c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6cActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label7.setText("7.\t-¿Con quienes vives en tu casa?");

        buttonGroup7.add(p7a);
        p7a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p7a.setText("a) Ambos padres y Hermanos    ");
        p7a.setName("1"); // NOI18N
        p7a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7aActionPerformed(evt);
            }
        });

        buttonGroup7.add(p7b);
        p7b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p7b.setText("b) Familiares           ");
        p7b.setName("2"); // NOI18N
        p7b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7bActionPerformed(evt);
            }
        });

        buttonGroup7.add(p7c);
        p7c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p7c.setText("c) Solo");
        p7c.setName("3"); // NOI18N

        label8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label8.setText("8.\t-¿Cuántos hermanos tienes?");

        buttonGroup8.add(p8a);
        p8a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p8a.setText("a) 1  a 2 ");
        p8a.setName("1"); // NOI18N

        buttonGroup8.add(p8b);
        p8b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p8b.setText("3 en adelante     ");
        p8b.setName("2"); // NOI18N

        buttonGroup8.add(p8c);
        p8c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p8c.setText("c) Ninguno");
        p8c.setName("3"); // NOI18N

        label9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label9.setText("9.-¿A qué edad has sufrido la pérdida de algún ser cercano?");

        buttonGroup9.add(p9a);
        p9a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p9a.setText("a) Antes de los 10 años    ");
        p9a.setName("1"); // NOI18N

        buttonGroup9.add(p9b);
        p9b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p9b.setText("c) Nunca");
        p9b.setName("2"); // NOI18N

        buttonGroup9.add(p9c);
        p9c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p9c.setText("c) 5 días-6 días");
        p9c.setName("3"); // NOI18N

        label10.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label10.setText("10.-¿Cómo consideras que es tu relación con tus familiares?");

        buttonGroup10.add(p10a);
        p10a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p10a.setText("a) Excelente   ");
        p10a.setName("1"); // NOI18N

        buttonGroup10.add(p10b);
        p10b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p10b.setText("b) Buena    ");
        p10b.setName("2"); // NOI18N

        buttonGroup10.add(p10c);
        p10c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p10c.setText("c) Mala");
        p10c.setName("3"); // NOI18N

        label11.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label11.setText("11.-¿Cómo consideras que es tu relación con tu padre?");

        buttonGroup11.add(p11a);
        p11a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p11a.setText("a) Excelente   ");
        p11a.setName("1"); // NOI18N

        buttonGroup11.add(p11b);
        p11b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p11b.setText("b) Buena    ");
        p11b.setName("2"); // NOI18N
        p11b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p11bActionPerformed(evt);
            }
        });

        buttonGroup11.add(p11c);
        p11c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p11c.setText("c) Mala");
        p11c.setName("3"); // NOI18N

        label12.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label12.setText("12.-¿Cómo consideras que es tu relación con tu madre?");

        buttonGroup12.add(p12a);
        p12a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p12a.setText("a) Excelente   ");
        p12a.setName("1"); // NOI18N

        buttonGroup12.add(p12b);
        p12b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p12b.setText("b) Buena    ");
        p12b.setName("2"); // NOI18N
        p12b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p12bActionPerformed(evt);
            }
        });

        buttonGroup12.add(p12c);
        p12c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p12c.setText("c) Mala");
        p12c.setName("3"); // NOI18N
        p12c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p12cActionPerformed(evt);
            }
        });

        label13.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label13.setText("13.-¿Tienes familiares con problemas psicológicos?");

        buttonGroup13.add(p13a);
        p13a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p13a.setText("a) Familiar directo      ");
        p13a.setName("1"); // NOI18N

        buttonGroup13.add(p13b);
        p13b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p13b.setText("b) Familiar indirecto      ");
        p13b.setName("2"); // NOI18N

        buttonGroup13.add(p13c);
        p13c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p13c.setText("c) No tengo");
        p13c.setName("3"); // NOI18N

        label14.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label14.setText("14.\t-¿Durante tu infancia sufriste violencia (física, verbal, psicológica, etc)?");

        buttonGroup14.add(p14a);
        p14a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p14a.setText("a) Frecuentemente    ");
        p14a.setName("1"); // NOI18N
        p14a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p14aActionPerformed(evt);
            }
        });

        buttonGroup14.add(p14b);
        p14b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p14b.setText("b) Solo en algunas ocasiones    ");
        p14b.setName("2"); // NOI18N

        buttonGroup14.add(p14c);
        p14c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p14c.setText("c) Nunca ");
        p14c.setName("3"); // NOI18N

        label15.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label15.setText("15.\t-¿A cuántos grupos de amigos perteneces?");

        buttonGroup15.add(p15a);
        p15a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p15a.setText("a) 4 en adelante    ");
        p15a.setName("1"); // NOI18N
        p15a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p15aActionPerformed(evt);
            }
        });

        buttonGroup15.add(p15b);
        p15b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p15b.setText("b) 1-3    ");
        p15b.setName("2"); // NOI18N

        buttonGroup15.add(p15c);
        p15c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p15c.setText("c) Ninguno");
        p15c.setName("3"); // NOI18N

        label16.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label16.setText("16.\t-¿Cuando tienes conflictos con alguna persona se los expreses?");

        buttonGroup16.add(p16a);
        p16a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p16a.setText("a) Siempre         ");
        p16a.setName("1"); // NOI18N

        buttonGroup16.add(p16b);
        p16b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p16b.setText("b) La mayoría de las veces ");
        p16b.setName("2"); // NOI18N

        buttonGroup16.add(p16c);
        p16c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p16c.setText("c) Rara vez");
        p16c.setName("3"); // NOI18N

        label17.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label17.setText("17.\t-¿Sueles contarle tus problemas a alguien?");

        buttonGroup17.add(p17a);
        p17a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p17a.setText("a) Siempre    ");
        p17a.setName("1"); // NOI18N

        buttonGroup17.add(p17b);
        p17b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p17b.setText("b) En ocasiones     ");
        p17b.setName("2"); // NOI18N
        p17b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p17bActionPerformed(evt);
            }
        });

        buttonGroup17.add(p17c);
        p17c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p17c.setText("c) Nunca");
        p17c.setName("3"); // NOI18N

        label18.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label18.setText("18.\t -¿Cuántas horas a la semana dedicas a hacer alguna actividad individual (Escuchar música, dibujar, leer, pintar, practicar algún deporte, etc)?");

        buttonGroup18.add(p18a);
        p18a.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p18a.setText("a) 11 en adelante    ");
        p18a.setName("1"); // NOI18N

        buttonGroup18.add(p18b);
        p18b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p18b.setText("b) 0-10     ");
        p18b.setName("2"); // NOI18N

        buttonGroup18.add(p18c);
        p18c.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p18c.setText("c) No dedico tiempo ");
        p18c.setName("3"); // NOI18N

        label19.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label19.setText("19.\t-¿Te has sentido discriminado?");

        buttonGroup19.add(p19a);
        p19a.setText("a) Nunca   ");
        p19a.setName("1"); // NOI18N

        buttonGroup19.add(p19b);
        p19b.setText("b) En ocasiones    ");
        p19b.setName("2"); // NOI18N

        buttonGroup19.add(p19c);
        p19c.setText("c) Siempre");
        p19c.setName("3"); // NOI18N

        label20.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label20.setText("20.-¿Qué tan frecuentemente te sientes desmotivado?");

        buttonGroup20.add(p20a);
        p20a.setText("a) Nunca   ");
        p20a.setName("1"); // NOI18N

        buttonGroup20.add(p20b);
        p20b.setText("b) En ocasiones    ");
        p20b.setName("2"); // NOI18N

        buttonGroup20.add(p20c);
        p20c.setText("c) Siempre");
        p20c.setName("3"); // NOI18N

        label21.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label21.setText("21.\t-¿Qué tan frecuentemente te sientes motivado?");

        buttonGroup21.add(p21a);
        p21a.setText("a) Nunca   ");
        p21a.setName("1"); // NOI18N

        buttonGroup21.add(p21b);
        p21b.setText("b) En ocasiones    ");
        p21b.setName("2"); // NOI18N

        buttonGroup21.add(p21c);
        p21c.setText("c) Siempre");
        p21c.setName("3"); // NOI18N

        label22.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label22.setText("22.\t-¿Sueles maltratar a las personas siendo grosero con ellos?");

        buttonGroup22.add(p22a);
        p22a.setText("a) Nunca   ");
        p22a.setName("1"); // NOI18N

        buttonGroup22.add(p22b);
        p22b.setText("b) En ocasiones    ");
        p22b.setName("2"); // NOI18N
        p22b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p22bActionPerformed(evt);
            }
        });

        buttonGroup22.add(p22c);
        p22c.setText("c) Siempre");
        p22c.setName("3"); // NOI18N

        label23.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label23.setText("23.\t-¿Reprimes tus emociones?");

        buttonGroup23.add(p23a);
        p23a.setText("a) Nunca   ");
        p23a.setName("1"); // NOI18N

        buttonGroup23.add(p23b);
        p23b.setText("b) En ocasiones    ");
        p23b.setName("2"); // NOI18N

        buttonGroup23.add(p23c);
        p23c.setText("c) Siempre");
        p23c.setName("3"); // NOI18N

        label24.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label24.setText("24.-¿Cómo consideras que es tu personalidad?");

        buttonGroup24.add(p24a);
        p24a.setText("a) Extrobertido    ");
        p24a.setName("1"); // NOI18N

        buttonGroup24.add(p24b);
        p24b.setText("b) Introvertido   ");
        p24b.setName("2"); // NOI18N
        p24b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p24bActionPerformed(evt);
            }
        });

        buttonGroup24.add(p24c);
        p24c.setText("c) Ambos");
        p24c.setName("3"); // NOI18N

        label25.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label25.setText("25.\t-¿Tienes alguna creencia religiosa?");

        buttonGroup25.add(p25a);
        p25a.setText("a) Si creo en Dios      ");
        p25a.setName("1"); // NOI18N
        p25a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p25aActionPerformed(evt);
            }
        });

        buttonGroup25.add(p25b);
        p25b.setText("b) Soy agnóstico                        ");
        p25b.setName("2"); // NOI18N

        buttonGroup25.add(p25c);
        p25c.setText("c) No creo en nada superior ");
        p25c.setName("3"); // NOI18N

        label26.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label26.setText("26.\t-¿Generalmente que tan común es que sientas ansias?");

        buttonGroup26.add(p26a);
        p26a.setText("a) Muy común    ");
        p26a.setName("1"); // NOI18N
        p26a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p26aActionPerformed(evt);
            }
        });

        buttonGroup26.add(p26b);
        p26b.setText("b) Rara vez    ");
        p26b.setName("2"); // NOI18N

        buttonGroup26.add(p26c);
        p26c.setText("c) En ocasiones");
        p26c.setName("3"); // NOI18N
        p26c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p26cActionPerformed(evt);
            }
        });

        label27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label27.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label27.setText("30.\t-¿Qué tan estresante es tu trabajo?");

        buttonGroup29.add(p29a);
        p29a.setText("a) Excelente");
        p29a.setToolTipText("");
        p29a.setActionCommand("");
        p29a.setName("1"); // NOI18N

        buttonGroup27.add(p27b);
        p27b.setText("b) 0-20");
        p27b.setName("2"); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup27.add(p27c);
        p27c.setText("c) 0");
        p27c.setName("3"); // NOI18N

        label28.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label28.setText("27.\t-¿Cuántas horas trabajas a la semana?");

        buttonGroup27.add(p27a);
        p27a.setText("a) 21-40");
        p27a.setName("1"); // NOI18N

        buttonGroup28.add(p28b);
        p28b.setText("b) Un poco cansado");
        p28b.setName("2"); // NOI18N
        p28b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p28bActionPerformed(evt);
            }
        });

        buttonGroup28.add(p28c);
        p28c.setText("c)Nada cansado");
        p28c.setName("3"); // NOI18N
        p28c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p28cActionPerformed(evt);
            }
        });

        label29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label29.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label29.setText("28.\t-¿Qué tan cansado consideras que es tu trabajo?");

        buttonGroup28.add(p28a);
        p28a.setText("a) Muy cansado");
        p28a.setToolTipText("");
        p28a.setActionCommand("");
        p28a.setName("1"); // NOI18N

        buttonGroup29.add(p29b);
        p29b.setText("b)Poco estresante");
        p29b.setName("2"); // NOI18N
        p29b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p29bActionPerformed(evt);
            }
        });

        buttonGroup29.add(p29c);
        p29c.setText("c)Nada estresante");
        p29c.setName("3"); // NOI18N
        p29c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p29cActionPerformed(evt);
            }
        });

        label30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label30.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label30.setText("29.-¿Cómo consideras tu ambiente laboral?");

        buttonGroup31.add(p31a);
        p31a.setText("a) Si");
        p31a.setToolTipText("");
        p31a.setActionCommand("");
        p31a.setName("1"); // NOI18N

        buttonGroup31.add(p31b);
        p31b.setText("b)No");
        p31b.setName("2"); // NOI18N
        p31b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p31bActionPerformed(evt);
            }
        });

        label31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label31.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        label31.setText("31.-¿Tienes o has tenido depresión?");

        buttonGroup30.add(p30a);
        p30a.setText("a) Muy estresante");
        p30a.setToolTipText("");
        p30a.setActionCommand("");
        p30a.setName("1"); // NOI18N

        buttonGroup30.add(p30b);
        p30b.setText("b)Poco estresante");
        p30b.setName("2"); // NOI18N
        p30b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p30bActionPerformed(evt);
            }
        });

        buttonGroup30.add(p30c);
        p30c.setText("c)Nada estresante");
        p30c.setName("3"); // NOI18N
        p30c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p30cActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p26a)
                        .addGap(18, 18, 18)
                        .addComponent(p26b)
                        .addGap(18, 18, 18)
                        .addComponent(p26c))
                    .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p12a)
                        .addGap(18, 18, 18)
                        .addComponent(p12b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p12c))
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p1a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p1b)
                        .addGap(18, 18, 18)
                        .addComponent(p1c))
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p2a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p2b)
                        .addGap(32, 32, 32)
                        .addComponent(p2c))
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p3a)
                        .addGap(18, 18, 18)
                        .addComponent(p3b)
                        .addGap(32, 32, 32)
                        .addComponent(p3c))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(449, 449, 449))
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p4a)
                                .addGap(45, 45, 45)
                                .addComponent(p4b)
                                .addGap(41, 41, 41)
                                .addComponent(p4c))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p5a)
                                .addGap(52, 52, 52)
                                .addComponent(p5b)
                                .addGap(45, 45, 45)
                                .addComponent(p5c))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p6a)
                                .addGap(18, 18, 18)
                                .addComponent(p6b)
                                .addGap(18, 18, 18)
                                .addComponent(p6c))))
                    .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p7a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p7b)
                        .addGap(18, 18, 18)
                        .addComponent(p7c))
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p8a)
                        .addGap(18, 18, 18)
                        .addComponent(p8b)
                        .addGap(18, 18, 18)
                        .addComponent(p8c))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p9a)
                        .addGap(27, 27, 27)
                        .addComponent(p9b)
                        .addGap(18, 18, 18)
                        .addComponent(p9c))
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(p10a)
                        .addGap(18, 18, 18)
                        .addComponent(p10b)
                        .addGap(34, 34, 34)
                        .addComponent(p10c))
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p11a)
                        .addGap(16, 16, 16)
                        .addComponent(p11b)
                        .addGap(18, 18, 18)
                        .addComponent(p11c))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p13a)
                        .addGap(18, 18, 18)
                        .addComponent(p13b)
                        .addGap(31, 31, 31)
                        .addComponent(p13c))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p15a)
                        .addGap(18, 18, 18)
                        .addComponent(p15b)
                        .addGap(26, 26, 26)
                        .addComponent(p15c))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p14a)
                        .addGap(18, 18, 18)
                        .addComponent(p14b)
                        .addGap(18, 18, 18)
                        .addComponent(p14c))
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p16a)
                        .addGap(18, 18, 18)
                        .addComponent(p16b)
                        .addGap(18, 18, 18)
                        .addComponent(p16c))
                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p17a)
                        .addGap(18, 18, 18)
                        .addComponent(p17b)
                        .addGap(18, 18, 18)
                        .addComponent(p17c))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p18a)
                        .addGap(18, 18, 18)
                        .addComponent(p18b)
                        .addGap(18, 18, 18)
                        .addComponent(p18c))
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p23a)
                        .addGap(18, 18, 18)
                        .addComponent(p23b)
                        .addGap(10, 10, 10)
                        .addComponent(p23c))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p22a)
                        .addGap(18, 18, 18)
                        .addComponent(p22b)
                        .addGap(18, 18, 18)
                        .addComponent(p22c))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p21a)
                        .addGap(18, 18, 18)
                        .addComponent(p21b)
                        .addGap(18, 18, 18)
                        .addComponent(p21c))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p20a)
                        .addGap(18, 18, 18)
                        .addComponent(p20b)
                        .addGap(18, 18, 18)
                        .addComponent(p20c))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p19a)
                        .addGap(18, 18, 18)
                        .addComponent(p19b)
                        .addGap(18, 18, 18)
                        .addComponent(p19c))
                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p27a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p27b)
                                .addGap(10, 10, 10)
                                .addComponent(p27c, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p28a)
                                .addGap(18, 18, 18)
                                .addComponent(p28b)
                                .addGap(18, 18, 18)
                                .addComponent(p28c))
                            .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p29a)
                                .addGap(18, 18, 18)
                                .addComponent(p29b)
                                .addGap(18, 18, 18)
                                .addComponent(p29c))))
                    .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p30a)
                        .addGap(18, 18, 18)
                        .addComponent(p30b)
                        .addGap(28, 28, 28)
                        .addComponent(p30c))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(p25a, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(p25b))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(p24a)
                                    .addGap(10, 10, 10)
                                    .addComponent(p24b)
                                    .addGap(18, 18, 18)
                                    .addComponent(p24c)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p25c))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(p31a)
                            .addGap(31, 31, 31)
                            .addComponent(p31b)
                            .addGap(216, 216, 216)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1a)
                    .addComponent(p1b)
                    .addComponent(p1c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2c)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p2a)
                        .addComponent(p2b)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3b)
                    .addComponent(p3c)
                    .addComponent(p3a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4a)
                    .addComponent(p4b)
                    .addComponent(p4c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5a)
                    .addComponent(p5b)
                    .addComponent(p5c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6a)
                    .addComponent(p6b)
                    .addComponent(p6c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p7a)
                    .addComponent(p7b)
                    .addComponent(p7c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p8a)
                    .addComponent(p8b)
                    .addComponent(p8c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p9a)
                    .addComponent(p9b)
                    .addComponent(p9c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p10a)
                    .addComponent(p10b)
                    .addComponent(p10c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p11a)
                    .addComponent(p11b)
                    .addComponent(p11c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p12a)
                    .addComponent(p12b)
                    .addComponent(p12c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p13a)
                    .addComponent(p13b)
                    .addComponent(p13c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p14a)
                    .addComponent(p14b)
                    .addComponent(p14c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p15a)
                    .addComponent(p15b)
                    .addComponent(p15c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p16a)
                    .addComponent(p16b)
                    .addComponent(p16c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p17a)
                    .addComponent(p17b)
                    .addComponent(p17c))
                .addGap(18, 18, 18)
                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p18a)
                    .addComponent(p18b)
                    .addComponent(p18c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p19a)
                    .addComponent(p19b)
                    .addComponent(p19c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p20a)
                    .addComponent(p20b)
                    .addComponent(p20c))
                .addGap(20, 20, 20)
                .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p21a)
                    .addComponent(p21b)
                    .addComponent(p21c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p22a)
                    .addComponent(p22b)
                    .addComponent(p22c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p23a)
                    .addComponent(p23b)
                    .addComponent(p23c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p24a)
                    .addComponent(p24b)
                    .addComponent(p24c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p25a)
                    .addComponent(p25b)
                    .addComponent(p25c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p26a)
                    .addComponent(p26b)
                    .addComponent(p26c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p27c, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p27b)
                        .addComponent(p27a)))
                .addGap(18, 18, 18)
                .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p28a)
                    .addComponent(p28b)
                    .addComponent(p28c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p29a)
                    .addComponent(p29b)
                    .addComponent(p29c))
                .addGap(2, 2, 2)
                .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p30a)
                    .addComponent(p30b)
                    .addComponent(p30c))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p31b)
                            .addComponent(p31a)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 66, Short.MAX_VALUE))
        );

        label18.getAccessibleContext().setAccessibleName("18.-¿Cuántas horas a la semana dedicas a hacer alguna actividad individual (Escuchar música, dibujar, leer, pintar, practicar algún deporte, etc)?");

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2081, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1aActionPerformed

    private void p1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1bActionPerformed

    private void p1cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1cActionPerformed

    private void p2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2aActionPerformed

    private void p2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2bActionPerformed

    private void p2cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2cActionPerformed

    private void p3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3bActionPerformed

    private void p3cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3cActionPerformed

    private void p5cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p5cActionPerformed

    private void p6cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p6cActionPerformed

    private void p7aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p7aActionPerformed

    private void p7bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p7bActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     String radioGrupo1 = "";
     String radioGrupo2 = "";
     String radioGrupo3 = "";
     String radioGrupo4 = "";
     String radioGrupo5 = "";
     String radioGrupo6 = "";
     String radioGrupo7 = "";
     String radioGrupo8 = "";
     String radioGrupo9 = "";
     String radioGrupo10 = "";
     String radioGrupo11 = "";
     String radioGrupo12= "";
     String radioGrupo13 = "";
     String radioGrupo14 = "";
     String radioGrupo15 = "";
     String radioGrupo16 = "";
     String radioGrupo17 = "";
     String radioGrupo18 = "";
     String radioGrupo19 = "";
     String radioGrupo20 = "";
     String radioGrupo21 = "";
     String radioGrupo22 = "";
     String radioGrupo23 = "";
     String radioGrupo24 = "";
     String radioGrupo25 = "";
     String radioGrupo26 = "";
     String radioGrupo27 = "";
     String radioGrupo28 = "";
     String radioGrupo29 = "";
     String radioGrupo30 = "";
     String radioGrupo31 = "";
    
       if(this.p1a.isSelected()){
            radioGrupo1= this.p1a.getName();}
        if(this.p1b.isSelected()){
            radioGrupo1= this.p1b.getName();}
        if(this.p1c.isSelected()){
            radioGrupo1= this.p1c.getName();} 
        
       if(this.p2a.isSelected()){
            radioGrupo2= this.p2a.getName();}
        if(this.p2b.isSelected()){
            radioGrupo2= this.p2b.getName();}
        if(this.p2c.isSelected()){
            radioGrupo2= this.p2c.getName();}
        
        if(this.p3a.isSelected()){
            radioGrupo3= this.p3a.getName();}
        if(this.p3b.isSelected()){
            radioGrupo3= this.p3b.getName();}
        if(this.p3c.isSelected()){
            radioGrupo3= this.p3c.getName();}    
        
        if(this.p4a.isSelected()){
            radioGrupo4= this.p4a.getName();}
        if(this.p4b.isSelected()){
            radioGrupo4= this.p4b.getName();}
        if(this.p4c.isSelected()){
            radioGrupo4= this.p4c.getName();}
        
        if(this.p5a.isSelected()){
            radioGrupo5= this.p5a.getName();}
        if(this.p5b.isSelected()){
            radioGrupo5= this.p5b.getName();}
        if(this.p5c.isSelected()){
            radioGrupo5= this.p5c.getName();}
        
        if(this.p6a.isSelected()){
            radioGrupo6= this.p6a.getName();}
        if(this.p6b.isSelected()){
            radioGrupo6= this.p6b.getName();}
        if(this.p6c.isSelected()){
            radioGrupo6= this.p6c.getName();}
      
        if(this.p7a.isSelected()){
            radioGrupo7= this.p7a.getName();}
        if(this.p7b.isSelected()){
            radioGrupo7= this.p7b.getName();}
        if(this.p7c.isSelected()){
            radioGrupo7= this.p7c.getName();}
        
        if(this.p8a.isSelected()){
            radioGrupo8= this.p8a.getName();}
        if(this.p8b.isSelected()){
            radioGrupo8= this.p8b.getName();}
        if(this.p8c.isSelected()){
            radioGrupo8= this.p8c.getName();}
        
        if(this.p9a.isSelected()){
            radioGrupo9= this.p9a.getName();}
        if(this.p9b.isSelected()){
            radioGrupo9= this.p9b.getName();}
        if(this.p9c.isSelected()){
            radioGrupo9= this.p9c.getName();}
        
        if(this.p10a.isSelected()){
            radioGrupo10 = this.p10a.getName();}
        if(this.p10b.isSelected()){
            radioGrupo10 = this.p10b.getName();}
        if(this.p10c.isSelected()){
            radioGrupo10 = this.p10c.getName();}
        
        if(this.p11a.isSelected()){
            radioGrupo11 = this.p11a.getName();}
        if(this.p11b.isSelected()){
            radioGrupo11 = this.p11b.getName();}
        if(this.p11c.isSelected()){
            radioGrupo11 = this.p11c.getName();}
        
        if(this.p12a.isSelected()){
            radioGrupo12 = this.p12a.getName();}
        if(this.p12b.isSelected()){
            radioGrupo12 = this.p12b.getName();}
        if(this.p12c.isSelected()){
            radioGrupo12 = this.p12c.getName();}
        
         if(this.p13a.isSelected()){
            radioGrupo13 = this.p13a.getName();}
        if(this.p13b.isSelected()){
            radioGrupo13 = this.p13b.getName();}
        if(this.p13c.isSelected()){
            radioGrupo13 = this.p13c.getName();}
       
         if(this.p14a.isSelected()){
            radioGrupo14 = this.p14a.getName();}
        if(this.p14b.isSelected()){
            radioGrupo14 = this.p14b.getName();}
        if(this.p14c.isSelected()){
            radioGrupo14 = this.p14c.getName();}
          
         if(this.p15a.isSelected()){
            radioGrupo15 = this.p15a.getName();}
        if(this.p15b.isSelected()){
            radioGrupo15 = this.p15b.getName();}
        if(this.p15c.isSelected()){
            radioGrupo15 = this.p15c.getName();}
        
        if(this.p16a.isSelected()){
            radioGrupo16 = this.p16a.getName();}
        if(this.p16b.isSelected()){
            radioGrupo16 = this.p16b.getName();}
        if(this.p16c.isSelected()){
            radioGrupo16 = this.p16c.getName();}
        
        if(this.p17a.isSelected()){
            radioGrupo17 = this.p17a.getName();}
        if(this.p17b.isSelected()){
            radioGrupo17 = this.p17b.getName();}
        if(this.p17c.isSelected()){
            radioGrupo17 = this.p17c.getName();}
        
        if(this.p18a.isSelected()){
            radioGrupo18 = this.p18a.getName();}
        if(this.p18b.isSelected()){
            radioGrupo18 = this.p18b.getName();}
        if(this.p18c.isSelected()){
            radioGrupo18 = this.p18c.getName();}
        
        if(this.p19a.isSelected()){
            radioGrupo19 = this.p19a.getName();}
        if(this.p19b.isSelected()){
            radioGrupo19 = this.p19b.getName();}
        if(this.p19c.isSelected()){
            radioGrupo19 = this.p19c.getName();}
        
        if(this.p20a.isSelected()){
            radioGrupo20 = this.p20a.getName();}
        if(this.p20b.isSelected()){
            radioGrupo20 = this.p20b.getName();}
        if(this.p20c.isSelected()){
            radioGrupo20 = this.p20c.getName();}
        
        if(this.p21a.isSelected()){
            radioGrupo21 = this.p21a.getName();}
        if(this.p21b.isSelected()){
            radioGrupo21 = this.p21b.getName();}
        if(this.p21c.isSelected()){
            radioGrupo21 = this.p21c.getName();}
        
        if(this.p22a.isSelected()){
            radioGrupo22 = this.p22a.getName();}
        if(this.p22b.isSelected()){
            radioGrupo22 = this.p22b.getName();}
        if(this.p22c.isSelected()){
            radioGrupo22= this.p22c.getName();}
        
        if(this.p23a.isSelected()){
            radioGrupo23 = this.p23a.getName();}
        if(this.p23b.isSelected()){
            radioGrupo23 = this.p23b.getName();}
        if(this.p23c.isSelected()){
            radioGrupo23 = this.p23c.getName();}
        
        if(this.p24a.isSelected()){
            radioGrupo24 = this.p24a.getName();}
        if(this.p24b.isSelected()){
            radioGrupo24 = this.p24b.getName();}
        if(this.p24c.isSelected()){
            radioGrupo24 = this.p24c.getName();}
        
        if(this.p25a.isSelected()){
            radioGrupo25 = this.p25a.getName();}
        if(this.p25b.isSelected()){
            radioGrupo25 = this.p25b.getName();}
        if(this.p25c.isSelected()){
            radioGrupo25 = this.p25c.getName();}
        
        if(this.p26a.isSelected()){
            radioGrupo26 = this.p26a.getName();}
        if(this.p26b.isSelected()){
            radioGrupo26 = this.p26b.getName();}
        if(this.p26c.isSelected()){
            radioGrupo26 = this.p26c.getName();}
        
        if(this.p27a.isSelected()){
            radioGrupo27 = this.p27a.getName();}
        if(this.p27b.isSelected()){
            radioGrupo27 = this.p27b.getName();}
        if(this.p27c.isSelected()){
            radioGrupo27 = this.p27c.getName();}
        
        if(this.p28a.isSelected()){
            radioGrupo28 = this.p28a.getName();}
        if(this.p28b.isSelected()){
            radioGrupo28 = this.p28b.getName();}
        if(this.p28c.isSelected()){
            radioGrupo28 = this.p28c.getName();}
        
        if(this.p29a.isSelected()){
            radioGrupo29 = this.p29a.getName();}
        if(this.p29b.isSelected()){
            radioGrupo29 = this.p29b.getName();}
        if(this.p29c.isSelected()){
            radioGrupo29 = this.p29c.getName();}
        
        if(this.p30a.isSelected()){
            radioGrupo30 = this.p30a.getName();}
        if(this.p30b.isSelected()){
            radioGrupo30 = this.p30b.getName();}
        if(this.p30c.isSelected()){
            radioGrupo30 = this.p30c.getName();}
        
         if(this.p31a.isSelected()){
            radioGrupo31 = this.p31a.getName();}
        if(this.p31b.isSelected()){
            radioGrupo31 = this.p31b.getName();}
        
        try {
            FileWriter fichero= new FileWriter("rutaParaF\\ejemplo.arff");//ruta para guarda el archivo .Arff
            fichero.write("@relation srcejemplo2\n");
            fichero.write("@attribute p1 numeric\n");
            fichero.write("@attribute p2 numeric\n");
            fichero.write("@attribute p3 numeric\n");
            fichero.write("@attribute p4 numeric\n");
            fichero.write("@attribute p5 numeric\n");
            fichero.write("@attribute p6 numeric\n");
            fichero.write("@attribute p7 numeric\n");
            fichero.write("@attribute p8 numeric\n");
            fichero.write("@attribute p9 numeric\n");
            fichero.write("@attribute p10 numeric\n");
            fichero.write("@attribute p11 numeric\n");
            fichero.write("@attribute p12 numeric\n");
            fichero.write("@attribute p13 numeric\n");
            fichero.write("@attribute p14 numeric\n");
            fichero.write("@attribute p15 numeric\n");
            fichero.write("@attribute p16 numeric\n");
            fichero.write("@attribute p17 numeric\n");
            fichero.write("@attribute p18 numeric\n");
            fichero.write("@attribute p19 numeric\n");
            fichero.write("@attribute p20 numeric\n");
            fichero.write("@attribute p21 numeric\n");
            fichero.write("@attribute p22 numeric\n");
            fichero.write("@attribute p23 numeric\n");
            fichero.write("@attribute p24 numeric\n");
            fichero.write("@attribute p25 numeric\n");
            fichero.write("@attribute p26 numeric\n");
            fichero.write("@attribute p27 numeric\n");
            fichero.write("@attribute p28 numeric\n");
            fichero.write("@attribute p29 numeric\n");
            fichero.write("@attribute p30 numeric\n");
            fichero.write("@attribute class {1,2}\n\n");
            fichero.write("@data\n");  
            fichero.write(radioGrupo1 +"," + radioGrupo2 + "," + radioGrupo3 + "," + radioGrupo4 + "," +  radioGrupo5 + "," 
             + radioGrupo6 +  "," + radioGrupo7 + "," + radioGrupo8 + "," + radioGrupo9 + "," + radioGrupo10 + "," 
             + radioGrupo11 + "," + radioGrupo12 + "," + radioGrupo13 + "," +radioGrupo14 + "," + radioGrupo15 + "," 
             + radioGrupo16 + "," + radioGrupo17 + "," + radioGrupo18 + "," + radioGrupo19 + "," + radioGrupo20 + "," 
             + radioGrupo21 + "," + radioGrupo22 + "," + radioGrupo23 + "," + radioGrupo24 +"," + radioGrupo25 + "," 
             + radioGrupo26 + "," + radioGrupo27 + "," + radioGrupo28 + "," + radioGrupo29 + "," + radioGrupo30 + "," + radioGrupo31);
            fichero.close();
             
  
        
        }catch (Exception ex) {
             Logger.getLogger(Prediccion.class.getName()).log(Level.SEVERE, null, ex);
}
        
        
        
              
        
        



                
          
             
           
             
             //mensaje JOptionPane.showMessageDialog(null, "SE INSERTARON LOS DATOS CORRECTAMENTE");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void p11bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p11bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p11bActionPerformed

    private void p12bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p12bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p12bActionPerformed

    private void p12cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p12cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p12cActionPerformed

    private void p14aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p14aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p14aActionPerformed

    private void p15aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p15aActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_p15aActionPerformed

    private void p17bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p17bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p17bActionPerformed

    private void p22bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p22bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p22bActionPerformed

    private void p24bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p24bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p24bActionPerformed

    private void p25aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p25aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p25aActionPerformed

    private void p26aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p26aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p26aActionPerformed

    private void p28bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p28bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p28bActionPerformed

    private void p28cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p28cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p28cActionPerformed

    private void p29bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p29bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p29bActionPerformed

    private void p29cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p29cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p29cActionPerformed

    private void p31bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p31bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p31bActionPerformed

    private void p26cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p26cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p26cActionPerformed

    private void p30bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p30bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p30bActionPerformed

    private void p30cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p30cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p30cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncuestaDepresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncuestaDepresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncuestaDepresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncuestaDepresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prediccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup21;
    private javax.swing.ButtonGroup buttonGroup22;
    private javax.swing.ButtonGroup buttonGroup23;
    private javax.swing.ButtonGroup buttonGroup24;
    private javax.swing.ButtonGroup buttonGroup25;
    private javax.swing.ButtonGroup buttonGroup26;
    private javax.swing.ButtonGroup buttonGroup27;
    private javax.swing.ButtonGroup buttonGroup28;
    private javax.swing.ButtonGroup buttonGroup29;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup30;
    private javax.swing.ButtonGroup buttonGroup31;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label3;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JRadioButton p10a;
    private javax.swing.JRadioButton p10b;
    private javax.swing.JRadioButton p10c;
    private javax.swing.JRadioButton p11a;
    private javax.swing.JRadioButton p11b;
    private javax.swing.JRadioButton p11c;
    private javax.swing.JRadioButton p12a;
    private javax.swing.JRadioButton p12b;
    private javax.swing.JRadioButton p12c;
    private javax.swing.JRadioButton p13a;
    private javax.swing.JRadioButton p13b;
    private javax.swing.JRadioButton p13c;
    private javax.swing.JRadioButton p14a;
    private javax.swing.JRadioButton p14b;
    private javax.swing.JRadioButton p14c;
    private javax.swing.JRadioButton p15a;
    private javax.swing.JRadioButton p15b;
    private javax.swing.JRadioButton p15c;
    private javax.swing.JRadioButton p16a;
    private javax.swing.JRadioButton p16b;
    private javax.swing.JRadioButton p16c;
    private javax.swing.JRadioButton p17a;
    private javax.swing.JRadioButton p17b;
    private javax.swing.JRadioButton p17c;
    private javax.swing.JRadioButton p18a;
    private javax.swing.JRadioButton p18b;
    private javax.swing.JRadioButton p18c;
    private javax.swing.JRadioButton p19a;
    private javax.swing.JRadioButton p19b;
    private javax.swing.JRadioButton p19c;
    private javax.swing.JRadioButton p1a;
    private javax.swing.JRadioButton p1b;
    private javax.swing.JRadioButton p1c;
    private javax.swing.JRadioButton p20a;
    private javax.swing.JRadioButton p20b;
    private javax.swing.JRadioButton p20c;
    private javax.swing.JRadioButton p21a;
    private javax.swing.JRadioButton p21b;
    private javax.swing.JRadioButton p21c;
    private javax.swing.JRadioButton p22a;
    private javax.swing.JRadioButton p22b;
    private javax.swing.JRadioButton p22c;
    private javax.swing.JRadioButton p23a;
    private javax.swing.JRadioButton p23b;
    private javax.swing.JRadioButton p23c;
    private javax.swing.JRadioButton p24a;
    private javax.swing.JRadioButton p24b;
    private javax.swing.JRadioButton p24c;
    private javax.swing.JRadioButton p25a;
    private javax.swing.JRadioButton p25b;
    private javax.swing.JRadioButton p25c;
    private javax.swing.JRadioButton p26a;
    private javax.swing.JRadioButton p26b;
    private javax.swing.JRadioButton p26c;
    private javax.swing.JRadioButton p27a;
    private javax.swing.JRadioButton p27b;
    private javax.swing.JRadioButton p27c;
    private javax.swing.JRadioButton p28a;
    private javax.swing.JRadioButton p28b;
    private javax.swing.JRadioButton p28c;
    private javax.swing.JRadioButton p29a;
    private javax.swing.JRadioButton p29b;
    private javax.swing.JRadioButton p29c;
    private javax.swing.JRadioButton p2a;
    private javax.swing.JRadioButton p2b;
    private javax.swing.JRadioButton p2c;
    private javax.swing.JRadioButton p30a;
    private javax.swing.JRadioButton p30b;
    private javax.swing.JRadioButton p30c;
    private javax.swing.JRadioButton p31a;
    private javax.swing.JRadioButton p31b;
    private javax.swing.JRadioButton p3a;
    private javax.swing.JRadioButton p3b;
    private javax.swing.JRadioButton p3c;
    private javax.swing.JRadioButton p4a;
    private javax.swing.JRadioButton p4b;
    private javax.swing.JRadioButton p4c;
    private javax.swing.JRadioButton p5a;
    private javax.swing.JRadioButton p5b;
    private javax.swing.JRadioButton p5c;
    private javax.swing.JRadioButton p6a;
    private javax.swing.JRadioButton p6b;
    private javax.swing.JRadioButton p6c;
    private javax.swing.JRadioButton p7a;
    private javax.swing.JRadioButton p7b;
    private javax.swing.JRadioButton p7c;
    private javax.swing.JRadioButton p8a;
    private javax.swing.JRadioButton p8b;
    private javax.swing.JRadioButton p8c;
    private javax.swing.JRadioButton p9a;
    private javax.swing.JRadioButton p9b;
    private javax.swing.JRadioButton p9c;
    // End of variables declaration//GEN-END:variables
}
